

###
POST http://localhost:3000/fixedexpense HTTP/1.1
content-type: application/json
{
    "description":"description",
    "value":"value",
    "date":"date",
    "recurring":"recurring",
    "category":"category",
    "note":"note",
}

###
GET http://localhost:3000/fixedexpense HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/fixedexpense?date=19072004 & category=bolo HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/fixedexpense/1 HTTP/1.1
content-type: application/json

###
PUT http://localhost:3000/fixedexpense HTTP/1.1
content-type: application/json

###
DELETE  http://localhost:3000/fixedexpense HTTP/1.1
content-type: application/json